# Cloudflared Deployment for K3s
# Runs cloudflared as a Deployment with HA (2 replicas)
#
# Prerequisites:
#   kubectl create secret generic cloudflare-tunnel-credentials \
#     --namespace ingress-system \
#     --from-file=credentials.json=/path/to/credentials.json

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
  labels:
    app.kubernetes.io/component: networking

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: ingress-system
data:
  config.yaml: |
    tunnel: homelab-unified
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
      # All traffic goes to Traefik - it handles host-based routing
      - service: http://traefik.ingress-system.svc.cluster.local:80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: ingress-system
  labels:
    app: cloudflared
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: tunnel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloudflared
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2000"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: cloudflared
                topologyKey: kubernetes.io/hostname

      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532

      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.1.0
          imagePullPolicy: IfNotPresent
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 2000
              name: metrics
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: cloudflared-config
        - name: creds
          secret:
            secretName: cloudflare-tunnel-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: ingress-system
  labels:
    app: cloudflared
spec:
  selector:
    app: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
      protocol: TCP

---
# ServiceMonitor for Prometheus (if using prometheus-operator)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: ingress-system
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  endpoints:
    - port: metrics
      interval: 30s
